name = "focusdbot-proxy"
main = "src/worker.ts"
compatibility_date = "2024-05-01"

[vars]
# CLIENT_SECRET will be set via wrangler secret

[[kv_namespaces]]
binding = "SUMMARIES"
id = "276eb283921f4d3f815c3131f212d31a"


